Repository MishaliaPillay/HealthAppointmentSystem, pull requests merged in 2025-04, with the labels that each got.

#58 Feature/proivder medical prac provider
  Frontend/src/providers/paitient-provider/context.tsx
  Frontend/src/providers/paitient-provider/models.tsx
  Frontend/src/providers/providerMedicPrac-provider/actions.tsx
  Frontend/src/providers/providerMedicPrac-provider/context.tsx
  Frontend/src/providers/providerMedicPrac-provider/index.tsx
  Frontend/src/providers/providerMedicPrac-provider/models.tsx
  Frontend/src/providers/providerMedicPrac-provider/reducer.tsx
Labels: enhancement

#63 Feature/auth provider
  Frontend/src/providers/auth-provider/action.tsx
  Frontend/src/providers/auth-provider/actions.tsx
  Frontend/src/providers/auth-provider/context.tsx
  Frontend/src/providers/auth-provider/index.tsx
  Frontend/src/providers/auth-provider/models.tsx
  Frontend/src/providers/auth-provider/reducer.tsx
Labels: enhancement

#85 table fix
  Backend/healthap/10.0.1/aspnet-core/src/healthap.EntityFrameworkCore/Migrations/20250412224418_MappingDBContextEntities.cs
  Backend/healthap/10.0.1/aspnet-core/src/healthap.EntityFrameworkCore/Migrations/20250414150833_CleanFixMigration.Designer.cs
  Backend/healthap/10.0.1/aspnet-core/src/healthap.EntityFrameworkCore/Migrations/20250414150833_CleanFixMigration.cs
Labels: bug

#87 Feature/theme
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/public/images/logo.jpg
  Frontend/src/app/layout.tsx
  Frontend/src/app/page.module.css
  Frontend/src/app/page.tsx
  Frontend/src/components/dashboard/Header.tsx
  Frontend/src/components/provider-dashboard/header.tsx
Labels: enhancement

#103 Bugfix/state mangement
  .vs/slnx.sqlite
  .vs/slnx.sqlite-journal
  Frontend/src/app/login/page.tsx
  Frontend/src/app/patient-dashboard/profile/page.tsx
  Frontend/src/app/provider-dashboard/page.tsx
  Frontend/src/providers/auth-provider/actions.tsx
  Frontend/src/providers/users-provider/context.tsx
  Frontend/src/providers/users-provider/index.tsx
  Frontend/src/utils/decoder.ts
Labels: bug

#104 Bugfix/state mangement get current user
  Frontend/src/app/login/page.tsx
  Frontend/src/app/provider-dashboard/page.tsx
Labels: bug

#115 Feature/getCurrentPatientByUserId
  Backend/healthap/10.0.1/aspnet-core/src/healthap.Application/Services/PersonServices/PatientAppService.cs
  Backend/healthap/10.0.1/aspnet-core/src/healthap.Core/Domain/Persons/PatientManager.cs
  Backend/healthap/10.0.1/aspnet-core/src/healthap.Core/Domain/Persons/ProviderManager.cs
Labels: enhancement

#154 Appointment creation successfull in the back end
  Backend/healthap/10.0.1/aspnet-core/src/healthap.Application/Services/AppointmentServices/AppointmentAppService.cs
  Backend/healthap/10.0.1/aspnet-core/src/healthap.Application/Services/PersonServices/ProviderAppService.cs
  Backend/healthap/10.0.1/aspnet-core/src/healthap.Core/Domain/Appointments/AppointmentManager.cs
  Backend/healthap/10.0.1/aspnet-core/src/healthap.Core/Domain/Institution/Institution.cs
  Backend/healthap/10.0.1/aspnet-core/src/healthap.Core/Domain/Persons/ProviderManager.cs
Labels: enhancement, feature

#155 Feature/ai chatboard
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/app/patient-dashboard/face-scan/page.tsx
  Frontend/src/app/patient-dashboard/styles/aiStyle/style.tsx
  Frontend/src/components/bonus-feature/components/displayChatboard.tsx
  Frontend/src/components/bonus-feature/geminiService.ts
Labels: feature

#159 implement initial layout and design improvements
  Frontend/src/app/landing-page/page.tsx
  Frontend/src/app/landing-page/style.css
  Frontend/src/app/login/LoginSignup.tsx
  Frontend/src/app/login/login-page.module.css
  Frontend/src/app/page.tsx
  Frontend/src/utils/middleware.ts
Labels: feature

#162 fixing routing mismatch
  Frontend/src/app/login/page.tsx
Labels: feature

#166 Bug/form card layout
  Frontend/.vscode/settings.json
  Frontend/src/app/login/login-page.module.css
Labels: bug

#167 HOC applied successfully
  Frontend/src/app/patient-dashboard/page.tsx
  Frontend/src/app/provider-dashboard/page.tsx
  Frontend/src/hoc/withAuth.tsx
Labels: bug, enhancement

#168 Development with HOC applied
  Backend/healthap/10.0.1/aspnet-core/src/healthap.Application/Services/AppointmentServices/AppointmentAppService.cs
  Backend/healthap/10.0.1/aspnet-core/src/healthap.Web.Host/appsettings.json
  Frontend/.vscode/settings.json
  Frontend/src/app/landing-page/page.tsx
  Frontend/src/app/landing-page/style.css
  Frontend/src/app/login/LoginSignup.tsx
  Frontend/src/app/login/login-page.module.css
  Frontend/src/app/login/page.tsx
  Frontend/src/app/page.tsx
  Frontend/src/app/patient-dashboard/page.tsx
  Frontend/src/app/provider-dashboard/page.tsx
  Frontend/src/hoc/withAuth.tsx
  Frontend/src/utils/middleware.ts
Labels: bug, enhancement

#178 Feature/bonus2
  Frontend/.gitignore
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/app/globals.css
  Frontend/src/app/layout.tsx
  Frontend/src/app/patient-dashboard/face-scan/page.tsx
  Frontend/src/app/patient-dashboard/page.tsx
  Frontend/src/app/patient-dashboard/profile/page.tsx
  Frontend/src/app/provider-dashboard/appointments/page.tsx
  Frontend/src/app/provider-dashboard/page.tsx
  Frontend/src/app/provider-dashboard/profile/page.tsx
  Frontend/src/app/provider-dashboard/speech-summarizer/page.tsx
  Frontend/src/app/provider-dashboard/speech-summarizer/speech.module.css
  Frontend/src/components/bonus-feature/components/CameraDisplay.tsx
  Frontend/src/components/bonus-feature/components/ControlPanel.tsx
  Frontend/src/components/bonus-feature/components/EmotionDisplay.tsx
  Frontend/src/components/bonus-feature/components/ErrorMessage.tsx
  Frontend/src/components/bonus-feature/components/Header.tsx
  Frontend/src/components/bonus-feature/components/InstructionsPanel.tsx
  Frontend/src/components/bonus-feature/components/ResultsPanel.tsx
  Frontend/src/components/bonus-feature/components/WellnessInsights.tsx
  Frontend/src/components/bonus-feature/components/displayChatboard.tsx
  Frontend/src/components/bonus-feature/context/FaceAnalyzerContext.tsx
  Frontend/src/components/bonus-feature/face-analyzers/FaceAnalyzer.module.css
  Frontend/src/components/bonus-feature/face-analyzers/FaceAnalyzer.tsx
  Frontend/src/components/bonus-feature/face-analyzers/geminiService.ts
  Frontend/src/components/bonus-feature/face-analyzers/types.ts
  Frontend/src/components/bonus-feature/speech-recognition/SpeechRecognition.module.css
  Frontend/src/components/bonus-feature/speech-recognition/SpeechRecognition.tsx
  Frontend/src/components/dashboard/Sidebar.tsx
  Frontend/src/components/login-form/page.tsx
  Frontend/src/components/provider-availability/ProviderAvailabilityModal.tsx
  Frontend/src/components/sign-up-form/page.tsx
  Frontend/src/providers/providerInstituion-provider/index.tsx
  Frontend/src/utils/pdf-helper.ts
  Frontend/src/utils/summarizer.ts
  Frontend/src/utils/summarytypes.ts
  Frontend/src/utils/useSpeechRecognition.ts
  Frontend/src/utils/useSummarizer.ts
Labels: enhancement

#177 fixing the saves changes button plus also addig a loader
  Frontend/src/app/patient-dashboard/layout.tsx
  Frontend/src/app/patient-dashboard/profile/page.tsx
Labels: bug

#181 Feature/appointment display
  Backend/healthap/10.0.1/aspnet-core/src/healthap.Application/Services/AppointmentServices/AppointmentAppService.cs
  Backend/healthap/10.0.1/aspnet-core/src/healthap.Application/Services/AppointmentServices/Dtos/AppointResponseDto.cs
  Backend/healthap/10.0.1/aspnet-core/src/healthap.Application/Services/AppointmentServices/Dtos/AppointmentDto.cs
  Backend/healthap/10.0.1/aspnet-core/src/healthap.Application/Services/AppointmentServices/Dtos/ProviderAvailabiltyDto.cs
  Backend/healthap/10.0.1/aspnet-core/src/healthap.Application/Services/AppointmentServices/IAppointmentAppService.cs
  Backend/healthap/10.0.1/aspnet-core/src/healthap.Application/Services/AppointmentServices/Mappings/AppointmentMapper.cs
  Backend/healthap/10.0.1/aspnet-core/src/healthap.Application/Services/Institutions/InstitutionMapperProfile.cs
  Backend/healthap/10.0.1/aspnet-core/src/healthap.Application/Services/PersonServices/Dtos/ProviderResponseDto.cs
  Backend/healthap/10.0.1/aspnet-core/src/healthap.Application/Services/PersonServices/IProviderAppService.cs
  Backend/healthap/10.0.1/aspnet-core/src/healthap.Application/Services/PersonServices/ProviderAppService.cs
  Backend/healthap/10.0.1/aspnet-core/src/healthap.Core/Domain/Appointments/Appointment.cs
  Backend/healthap/10.0.1/aspnet-core/src/healthap.Core/Domain/Appointments/AppointmentManager.cs
  Backend/healthap/10.0.1/aspnet-core/src/healthap.Core/Domain/Persons/ProviderManager.cs
  Backend/healthap/10.0.1/aspnet-core/src/healthap.EntityFrameworkCore/EntityFrameworkCore/healthapDbContext.cs
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/app/provider-dashboard/appointments/page.tsx
  Frontend/src/app/provider-dashboard/page.tsx
  Frontend/src/components/appointments/editBookingModal.tsx
  Frontend/src/providers/appointment-provider/actions.tsx
  Frontend/src/providers/appointment-provider/context.tsx
  Frontend/src/providers/appointment-provider/index.tsx
  Frontend/src/providers/appointment-provider/models.tsx
  Frontend/src/providers/auth-provider/index.tsx
  Frontend/src/providers/paitient-provider/context.tsx
  Frontend/src/providers/paitient-provider/index.tsx
  Frontend/src/providers/providerInstituion-provider/index.tsx
  Frontend/src/providers/providerMedicPrac-provider/index.tsx
  Frontend/src/providers/users-provider/index.tsx
Labels: enhancement, feature

#184 adding toast pop up messages
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/components/login-form/page.tsx
  Frontend/src/components/sign-up-form/page.tsx
Labels: feature

#185 Bugfix/api key
  Backend/healthap/10.0.1/aspnet-core/src/healthap.Web.Host/appsettings.json
  Frontend/src/providers/appointment-provider/index.tsx
  Frontend/src/providers/paitient-provider/index.tsx
  Frontend/src/providers/providerMedicPrac-provider/index.tsx
  Frontend/src/providers/users-provider/index.tsx
Labels: bug, enhancement

#187 changed connection string
  Backend/healthap/10.0.1/aspnet-core/src/healthap.Web.Host/appsettings.json
Labels: bug, enhancement

#188 Development
  Backend/healthap/10.0.1/aspnet-core/src/healthap.Web.Host/appsettings.json
  Frontend/package-lock.json
  Frontend/package.json
  Frontend/src/components/login-form/page.tsx
  Frontend/src/components/sign-up-form/page.tsx
  Frontend/src/providers/appointment-provider/index.tsx
  Frontend/src/providers/paitient-provider/index.tsx
  Frontend/src/providers/providerMedicPrac-provider/index.tsx
  Frontend/src/providers/users-provider/index.tsx
Labels: bug, enhancement

#189 final booking
  Frontend/src/app/layout.tsx
  Frontend/src/app/patient-dashboard/booking-page/page.tsx
  Frontend/src/app/patient-dashboard/provider-times/provider-timeslot.tsx
  Frontend/src/app/provider-dashboard/page.tsx
  Frontend/src/components/provider-availability/ProviderAvailabilityModal.tsx
  Frontend/src/components/sign-up-form/page.tsx
  Frontend/src/providers/appointment-provider/actions.tsx
  Frontend/src/providers/appointment-provider/context.tsx
  Frontend/src/providers/appointment-provider/index.tsx
  Frontend/src/providers/appointment-provider/models.tsx
  Frontend/src/providers/institutionLocation-provider/context.tsx
  Frontend/src/providers/institutionLocation-provider/index.tsx
  Frontend/src/providers/paitient-provider/index.tsx
  Frontend/src/providers/provider-availibility/actions.tsx
  Frontend/src/providers/provider-availibility/context.tsx
  Frontend/src/providers/providerInstituion-provider/index.tsx
  Frontend/src/providers/providerMedicPrac-provider/index.tsx
  Frontend/src/providers/users-provider/index.tsx
Labels: enhancement

#186 Seperation features and making them have their own pages
  Frontend/src/app/patient-dashboard/face-scan/page.tsx
  Frontend/src/app/patient-dashboard/health-analyze/page.tsx
  Frontend/src/components/dashboard/Sidebar.tsx
Labels: bug

#192 IMAGE analyzer
  Frontend/src/app/patient-dashboard/styles/aiStyle/style.tsx
  Frontend/src/components/bonus-feature/components/displayChatboard.tsx
Labels: enhancement

#204 Bug/dashboard responsiveness
  Frontend/src/app/patient-dashboard/styles/aiStyle/style.tsx
Labels: bug

#203 dashboard is now responsive more than ever
  Frontend/src/app/patient-dashboard/styles/aiStyle/style.tsx
Labels: bug
